"""Adding visited at coulmn

Revision ID: 646a31e5a7c8
Revises: b3f37f8f442b
Create Date: 2026-09-09 16:04:48.675694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '646a31e5a7c8'
down_revision: Union[str, Sequence[str], None] = 'b3f37f8f442b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
