"""Added client ip

Revision ID: b3f37f8f442b
Revises: 3aef3180330e
Create Date: 2026-09-09 12:08:06.911388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3f37f8f442b'
down_revision: Union[str, Sequence[str], None] = '3aef3180330e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page_visits', sa.Column('client_ip', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page_visits', 'client_ip')
    # ### end Alembic commands ###
